FROM ubuntu:24.04
LABEL Description="Build environment"

ENV HOME /root

RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential \
    clang \
    cmake \
    gdb \
    wget

# Install python for tests
RUN apt-get -y --no-install-recommends install python3 python3-pip

# Install GitHub CLI
RUN mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
&& chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
&& apt install gh -y

# Add a script to create the symbolic links at runtime
RUN echo "ln -s /build/compile_commands.json /compile_commands.json" > /root/create_symlink.sh && \
    chmod +x /root/create_symlink.sh

# Install zsh
RUN apt-get update && apt-get install -y zsh && rm -rf /var/lib/apt/lists/*

# Install clang-format
RUN apt-get install clang-format -y

# Make zsh the default shell
RUN chsh -s $(which zsh)