name: AES Testing Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: pip install pytest

  test-keyExpansion:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run keyExpansion tests
        run: |
          cd ./src/functions/keyExpansion
          pytest keyExpansion-test.py

    